load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["cmd.go"],
    importpath = "github.com/motiejus/code/undocker/internal/cmd",
    visibility = ["//src/undocker:__subpackages__"],
)
