load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "rootfs_lib",
    srcs = ["rootfs.go"],
    importpath = "github.com/motiejus/code/undocker/rootfs",
    visibility = ["//visibility:public"],
)
