load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["lxcconfig.go"],
    importpath = "github.com/motiejus/code/undocker/lxc-config",
    visibility = ["//visibility:public"],
)
